<?php /*
        * Template Name: 
        *
        * Description: A page template that provides a key component of WordPress as a CMS
        * by meeting the need for a carefully crafted introductory page. The front page template
        * in Twenty Twelve consists of a page content area for adding text, images, video --
        *
        * @package WordPress
        * @subpackage Twenty Fifteen

        */?>
        <?php ob_start();?><!-- <mnbaa_SEPERATOR> "[\r\n  {\r\n    \"label\": \"Column\",\r\n    \"type\": \"column\",\r\n    \"columns\": [\r\n      []\r\n    ],\r\n    \"properties\": {\r\n      \"width\": \"12\",\r\n      \"offset\": \"0\"\r\n    }\r\n  },\r\n  {\r\n    \"label\": \"Container\",\r\n    \"type\": \"container\",\r\n    \"columns\": [\r\n      [\r\n        {\r\n          \"label\": \"Column\",\r\n          \"type\": \"column\",\r\n          \"columns\": [\r\n            [\r\n              {\r\n                \"type\": \"clear\",\r\n                \"label\": \"Clear\"\r\n              },\r\n              {\r\n                \"type\": \"text\",\r\n                \"properties\": {\r\n                  \"Text\": {\r\n                    \"input_type\": \"textarea\",\r\n                    \"value\": \"type your text here\"\r\n                  }\r\n                },\r\n                \"label\": \"text\"\r\n              },\r\n              {\r\n                \"type\": \"alert\",\r\n                \"properties\": {\r\n                  \"text\": {\r\n                    \"input_type\": \"textarea\",\r\n                    \"value\": \"type content here\"\r\n                  },\r\n                  \"image\": {\r\n                    \"input_type\": \"image\",\r\n                    \"value\": \"\"\r\n                  },\r\n                  \"background\": {\r\n                    \"input_type\": \"radio\",\r\n                    \"choices\": {\r\n                      \"gray\": \"gray\",\r\n                      \"orange\": \"orange\",\r\n                      \"light-gray\": \"light-gray\"\r\n                    },\r\n                    \"value\": \"gray\"\r\n                  }\r\n                },\r\n                \"label\": \"Alert\"\r\n              }\r\n            ]\r\n          ],\r\n          \"properties\": {\r\n            \"width\": \"8\",\r\n            \"offset\": \"0\"\r\n          }\r\n        }\r\n      ]\r\n    ],\r\n    \"properties\": {\r\n      \"fixed\": {\r\n        \"input_type\": \"radio\",\r\n        \"choices\": {\r\n          \"True\": \"true\",\r\n          \"False\": \"false\"\r\n        },\r\n        \"value\": \"true\"\r\n      }\r\n    }\r\n  }\r\n]"</mnbaa_SEPERATOR>--><?php ob_clean();?><?php do_shortcode("[qalep template id=82]"); ?>