<?php /*
        * Template Name: first template
        *
        * Description: A page template that provides a key component of WordPress as a CMS
        * by meeting the need for a carefully crafted introductory page. The front page template
        * in Twenty Twelve consists of a page content area for adding text, images, video --
        *
        * @package WordPress
        * @subpackage Twenty Thirteen

        */?>
        <?php ob_start();?><!-- <mnbaa_SEPERATOR> "[\r\n  {\r\n    \"label\": \"Container\",\r\n    \"type\": \"container\",\r\n    \"columns\": [\r\n      [\r\n        {\r\n          \"label\": \"Image\",\r\n          \"type\": \"image\"\r\n        },\r\n        {\r\n          \"type\": \"content_box\",\r\n          \"properties\": {\r\n            \"template\": {\r\n              \"input_type\": \"radio\",\r\n              \"choices\": {\r\n                \"template1\": \"box1\",\r\n                \"template2\": \"box2\",\r\n                \"template3\": \"box3\"\r\n              },\r\n              \"value\": \"box2\"\r\n            },\r\n            \"title\": \"TITLE OF THE BLOCK IN HERE\",\r\n            \"text\": {\r\n              \"input_type\": \"textarea\",\r\n              \"value\": \"love you\"\r\n            }\r\n          },\r\n          \"label\": \"Content_box\"\r\n        },\r\n        {\r\n          \"type\": \"divider\",\r\n          \"properties\": {\r\n            \"shape\": {\r\n              \"input_type\": \"radio\",\r\n              \"choices\": {\r\n                \"thin\": \"thin\",\r\n                \"dashed\": \"dashed\",\r\n                \"slash\": \"slash\"\r\n              },\r\n              \"value\": \"dashed\"\r\n            }\r\n          },\r\n          \"label\": \"Divider\"\r\n        },\r\n        {\r\n          \"type\": \"counting\",\r\n          \"properties\": {\r\n            \"percent\": \"34.2%\",\r\n            \"size\": \"300\",\r\n            \"borderWidth\": \"40\",\r\n            \"bgFill\": \"#f7f7f7\",\r\n            \"frFill\": \"#fa9011\",\r\n            \"textSize\": \"15\",\r\n            \"textColor\": \"#585858\"\r\n          },\r\n          \"label\": \"Counting\"\r\n        },\r\n        {\r\n          \"type\": \"clear\",\r\n          \"label\": \"Clear\"\r\n        }\r\n      ]\r\n    ],\r\n    \"properties\": {\r\n      \"fixed\": {\r\n        \"input_type\": \"radio\",\r\n        \"choices\": {\r\n          \"True\": \"true\",\r\n          \"False\": \"false\"\r\n        },\r\n        \"value\": \"true\"\r\n      }\r\n    }\r\n  }\r\n]"</mnbaa_SEPERATOR>--><?php ob_clean();?><?php do_shortcode("[qalep template id=1]"); ?>