<?php /*
        * Template Name: first template
        *
        * Description: A page template that provides a key component of WordPress as a CMS
        * by meeting the need for a carefully crafted introductory page. The front page template
        * in Twenty Twelve consists of a page content area for adding text, images, video --
        *
        * @package WordPress
        * @subpackage Twenty Thirteen

        */?>
        <?php ob_start();?><!-- <mnbaa_SEPERATOR> "[\r\n  {\r\n    \"type\": \"paragraph\",\r\n    \"properties\": {\r\n      \"slug\": \"www.facebook.com\",\r\n      \"link\": \"www.link.com\"\r\n    },\r\n    \"label\": \"Url\"\r\n  },\r\n  {\r\n    \"label\": \"Container\",\r\n    \"type\": \"container\",\r\n    \"columns\": [\r\n      [\r\n        {\r\n          \"type\": \"text\",\r\n          \"properties\": {\r\n            \"Text\": {\r\n              \"input_type\": \"textarea\",\r\n              \"value\": \"type your text here\"\r\n            }\r\n          },\r\n          \"label\": \"text\"\r\n        },\r\n        {\r\n          \"type\": \"testimonial\",\r\n          \"properties\": {\r\n            \"text\": {\r\n              \"input_type\": \"textarea\",\r\n              \"value\": \"is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknownis simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown\"\r\n            },\r\n            \"image\": {\r\n              \"input_type\": \"image\",\r\n              \"value\": \"\"\r\n            },\r\n            \"personName\": \"hoda\",\r\n            \"personPosition\": \"php devloper\",\r\n            \"size\": {\r\n              \"input_type\": \"radio\",\r\n              \"choices\": {\r\n                \"meduim\": \"6\",\r\n                \"large\": \"12\"\r\n              },\r\n              \"value\": \"6\"\r\n            },\r\n            \"template\": {\r\n              \"input_type\": \"radio\",\r\n              \"choices\": [\r\n                \"in box\",\r\n                \"with popup\"\r\n              ],\r\n              \"value\": \"with popup\"\r\n            }\r\n          },\r\n          \"label\": \"Testimonial\"\r\n        },\r\n        {\r\n          \"type\": \"post\",\r\n          \"properties\": {\r\n            \"numberposts\": \"2\",\r\n            \"post_type\": \"\",\r\n            \"pagination\": {\r\n              \"input_type\": \"radio\",\r\n              \"choices\": [\r\n                \"pagination-default\",\r\n                \"pagination-soft\",\r\n                \"pagination-color\",\r\n                \"pagination-cir\"\r\n              ],\r\n              \"value\": \"pagination-soft\"\r\n            }\r\n          },\r\n          \"label\": \"Post\"\r\n        }\r\n      ]\r\n    ],\r\n    \"properties\": {\r\n      \"fixed\": {\r\n        \"input_type\": \"radio\",\r\n        \"choices\": {\r\n          \"True\": \"true\",\r\n          \"False\": \"false\"\r\n        },\r\n        \"value\": \"true\"\r\n      }\r\n    }\r\n  }\r\n]"</mnbaa_SEPERATOR>--><?php ob_clean();?><?php do_shortcode("[qalep template id=1]"); ?>